# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC   RoundCode,
# MAGIC   RoundOrder,
# MAGIC   COUNT(*) AS matches
# MAGIC FROM gold_dev.default.fact_match_results
# MAGIC GROUP BY RoundCode, RoundOrder
# MAGIC ORDER BY RoundOrder;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT
# MAGIC   MatchSequence,
# MAGIC   SeasonId,
# MAGIC   Date,
# MAGIC   RoundCode,
# MAGIC   RoundOrder,
# MAGIC   CompetitionId,
# MAGIC   HomeTeamId,
# MAGIC   AwayTeamId
# MAGIC FROM gold_dev.default.match_sequence
# MAGIC ORDER BY MatchSequence
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from gold_dev.default.dim_rounds
# MAGIC order by RoundOrder;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- check dates in the match facts
# MAGIC
# MAGIC SELECT
# MAGIC   SeasonId,
# MAGIC   CompetitionId,
# MAGIC   MIN(Date)        AS first_date,
# MAGIC   MIN(RoundOrder) AS first_round_order,
# MAGIC   MIN(RoundCode)  AS first_round_code
# MAGIC FROM gold_dev.default.fact_match_results
# MAGIC GROUP BY SeasonId, CompetitionId
# MAGIC ORDER BY SeasonId, CompetitionId;

# COMMAND ----------

# MAGIC %sql
# MAGIC -- check dates in the match facts
# MAGIC
# MAGIC SELECT
# MAGIC   MIN(Date) AS first_date
# MAGIC FROM silver_dev.default.match_results_silver;
# MAGIC
